# Generated by Django 5.2 on 2025-05-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion_inicio', models.CharField(max_length=100)),
                ('ubicacion_fin', models.CharField(max_length=100)),
                ('longitud', models.DateField()),
                ('duracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='punto_interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('horarios', models.IntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='ruta.rutas')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=30)),
                ('num_celular', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('grupos', models.ManyToManyField(related_name='usuarios', to='ruta.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='rutas',
            name='usuarios',
            field=models.ManyToManyField(related_name='rutas', to='ruta.usuario'),
        ),
    ]
