# Generated by Django 5.2 on 2025-06-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_grupoalimenticio_unidaddemedida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='imagen_url',
        ),
    ]
