# Generated by Django 5.2 on 2025-06-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0005_remove_alimento_fuente_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valornutricional',
            name='cantidad_referencia',
        ),
        migrations.RemoveField(
            model_name='valornutricional',
            name='referencia_por_cantidad',
        ),
    ]
