# Generated by Django 5.2 on 2025-06-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0006_remove_valornutricional_cantidad_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valornutricional',
            name='porcentaje_vd',
        ),
    ]
